module.exports = {
    races: [
        'Invalid',
        'Blood Elf',
        'Draenei',
        'Dwarf',
        'Gnome',
        'Goblin',
        'Human',
        'Night Elf',
        'Orc',
        'Tauren',
        'Troll',
        'Undead',
        'Worgen',
        'Goblin2',
        'Murloc',
        'Demon',
        'Scourge',
        'Mechanical',
        'Elemental',
        'Ogre',
        'Beast',
        'Totem',
        'Nerubian',
        'Pirate',
        'Dragon',
        'Pet'
    ]
};
